using System;
using Oxide.Ext.Discord;
using Oxide.Ext.Discord.Interfaces;
using Oxide.Ext.Discord.Logging;

public readonly struct RejectHandler
{
	private readonly Action<Exception> _callback;

	private readonly IRejectable _rejectable;

	internal RejectHandler(Action<Exception> callback, IRejectable rejectable)
	{
		_callback = callback;
		_rejectable = rejectable;
	}

	internal void Reject(Exception exception)
	{
		try
		{
			_callback(exception);
		}
		catch (Exception ex)
		{
			DiscordExtension.GlobalLogger.Exception("An error occured during reject of Promise", ex);
			_rejectable.Reject(ex);
		}
	}
}
